spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/author_book
    username: postgres
    password: Dlbarmirze5678.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
