spring:
  application:
    name: movie-app

  datasource:
    url: jdbc:postgresql://localhost:5432/movie-app
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create
    show-sql: true

  liquibase:
    enabled: false

#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/course-student
#    username: postgres
#    password: Dlbarmirze5678.
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        # Optimistik kilidləməni söndür
#        optimistic_locking: false
#        # Əlavə təhlükəsizlik üçün
#        jdbc:
#          batch_size: 30
#          batch_versioned_data: true
#
#  liquibase:
#    change-log: classpath:/db.changelog/changelog-master.yml
#
#  logging:
#    level:
#      liquibase: DEBUG
#      org:
#        hibernate:
#          engine:
#            internal: DEBUG  # Hibernate daxili prosesləri görmək üçün
#          event:
#            internal: DEBUG
#
#server:
#  port: 8081